addons:
  apt:
    packages:
    - p7zip-full
language: node_js
node_js:
- 10
install:
- npm install
script:
- oclif-dev pack
jobs:
  include:
  - stage: Linux
    os: linux
    deploy:
      edge: true
      provider: releases
      token:
        secure: sLRR880fqZAwubqiGRGia8Wf+Jg0SL06O0nL55upGOcWozuWa1uWzTdmcECdB5sPVs4HfCmtppRY5Ooptn67+gS+/laMg321fORIDxG/Vu8QEiPCHtJdNRN1Kr8HZp/847RhOXl7+51kXuR5hgciudKs3ELXshlvF1dBq36a+ErdUPUu6WFBH2Joyb3oJYd2+aMNnwgRl2OEKeHepCdkndBaJqwBKQ65xFCU/ZjH4oNPQs7WEosnDhuPkMQHyydQ+arxCCdqMzIH4R4FeLutOgfyth/0Ji9PBu1KeTEXeCnwrG6kJpO7cZQzmot4K5mUDwQxEzuLUKllZbYSwEcqmo1ud7NRRIZnUQfd9e/3f59ksxSOFSsQckPNT5I6AM+0THGHagOOTkaufU5GkpdSra07B8P7L6pyuPBYYRlGWFf0AiWqXOkZyJ8+qSNafuyD3jmXqs3ROTzKWxmIMsRE3fATDyWmNSrR20UnwffJi5OAnysjgauReqgKI0PgxO53QbUoFUNxRVMLz6UPSfkznkk+dFa1qIRMvU6HGKC2oBBUWv8zeD5YD9NSL2fiiIz0mr+Xc9v3V3gLrhSZBEcje33HUh5r+1Cz/xCwAikXnY23F8fG2vwphphiW2nDCVzbwVPOH2W+6L8Nzoc/xK0e0s15ODSTVs8bZ8SC54muE3A=
      file: dist/**/**
      file_glob: true
      overwrite: true
      cleanup: false
      on:
        repo: pm98zz-c/ce-dev
        # tags: true
      draft: true