addons:
  apt:
    packages:
    - p7zip-full
language: node_js
node_js:
- 10
install:
- npm install
script:
- oclif-dev pack
deploy:
  edge: true
  provider: releases
  file: dist/**/**
  file_glob: true
  overwrite: true
  cleanup: false
  api_key:
    secure: AAuerjQVILKsuN93FrcbbzcxsmOxPKgZNEnb5EQo1b4wzxM4s+Q9Jb7FnFRTnAT9VjyhGTIxV9NKT7PWts4zI1LEDjnWcu3Uv+YlW92RVnlh0OeGV2J0QA4UkhkBSajIJtVZnpx21BtNxdGtKD4kBdRKwjQHENBWzakl6CJNLzQtbpQJlT1viam6Fx6DTgwfj95rDJGYv6qxCuAKCo1o+4yj8oNzVdunZZYw8e+uQiaghVIjdxtVKigaxmyXHQ6A+T4lYqoz9QdyJbw0lLjcXHBzWO+9VJ/qXoPo0HpbImV5ak6Y5xFGxV9UinCPvgPPN6BwhsHPxk0tU/wy8wwo4FNl9GEYouBLoZBxjwa+MpWzW+7O9y/ibR5DqZ2DjMV4HITWr7NfrKACorR2gtxxTLG+Th+jiEBuiskh7m/0Ykzm1o3v34RNT91XHp/jGVjvNSDtteW/Aqm0SV3YNOvEzo8RzQosjxM3P3AbaBMfk2Zm5IbuKNQ66wbGCT+vuL5a00/FvpLLEvl2LcXENpXjuNumPG1r8tzyGXx/G8oq+CPexCrOuuWm06og1R/pp4xkMVunV/4ohB4cIgGRUwEEDIqkAq2ICd+iFH5wAYzXSsZFSe65T6d7R7FX/xDAaT3XKuFiW82UKQkaBE97VS9H1gkn1SSaKfd9B+GR89/UkiI=
  on:
    repo: codeenigma/ce-dev
    branch: 1.x
  draft: true