addons:
  apt:
    packages:
    - p7zip-full
language: node_js
node_js:
- 10
install:
- npm install
script:
- oclif-dev pack
deploy:
  provider: releases
  api_key:
    secure: ahIe76VlhJzYuO5CJgByD9MDrtazrG+zwK6Zi0mjyDjo1qnABGc++rJzEKjVjAi+mP3mL9FHzlJ+a4zpuaarTsrjt/YLPbMeQ5KCpuEg9T5g1iCguE/ykc+hLL28ACHHSnfOKAW9ZZQUkuvYBpMWWApAlFDPnzKrcnbDt0rIuuVPdTn9f4mmFZAXBzXqH7yQ+wR0GryQRrj7nXembYvNayf6UobsENK/lPmY+1dLGHoGv25FW+frYCj2jqwbrFRxn+2FNlFxj4VLsIXPyRAeqbl+a+ifxPrxyPqgPkWxoSYWwSDlPmRvV4A57AbQDeBQBSmii8IDMdeL8CDJ/l+yOM8JprqzJ0Th1KqB6Z67PzCrm468Dac7Ud79eNTiVYVTjQa8XgG8Xzm2cqbBQZYfRtfOtp0ltTe/mRcV0f82EgjhpAnHIMgUQvtY9LLCkTjS1z8lokOE0E0URjCNZFoSpNGqar6r++E7VZKdp9RgEguxi0Qpa6YOLakQDXEo7riz9EvEaTbqJLRlhk7GQtKL0KUTXh5uE2vhJKpr3EGKoOT3cczIvGkIxVSlT8HO62bzRyd//4Ku4XtrfoAHkF4HC6xDQCfL6dFeKSn6QmMf9RvQxZgGxATHyQitz1/rKO/0DJic1RDcJn6KVuk7rzXUzR5QIjSX4qMd5NALoPzxsZs=
  file: dist/**/**
  on:
    repo: codeenigma/ce-dev
    branch: 1.x
