language: c
os: linux
dist: xenial
services:
  - docker
jobs:
  include:
    - name: Lint
      os: linux
      install:
        - yarn install
      script: 
        - yarn eslint src
      language: node_js
      node_js: 12
    - name: Pack
      os: linux
      addons:
        apt:
          packages:
          - p7zip-full      
      script: yarn oclif-dev pack
      language: node_js
      node_js: 12
    - name: Build and test
      if: branch != '1.x'
      os: linux
      language: node_js
      node_js: 12
      addons:
        apt:
          packages:
          - p7zip-full
          - libnss3-tools
          - wget
      install:
        - yarn install
        - wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/mkcert-v1.4.1-linux-amd64 -O /tmp/mkcert
        - sudo mv /tmp/mkcert /usr/local/bin
        - sudo chmod +x /usr/local/bin/mkcert
      script: 
        - /bin/sh docker-images/export.sh latest
        - /bin/sh templates/prebuild.sh
    - name: Build and publish
      os: linux
      language: node_js
      node_js: 12
      addons:
        apt:
          packages:
          - p7zip-full
          - libnss3-tools
          - wget
      install:
        - yarn install
        - wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/mkcert-v1.4.1-linux-amd64 -O /tmp/mkcert
        - sudo mv /tmp/mkcert /usr/local/bin
        - sudo chmod +x /usr/local/bin/mkcert
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - /bin/sh docker-images/export.sh latest --push
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - /bin/sh templates/prebuild.sh --push
        - yarn oclif-dev pack
      deploy:
        edge: true
        provider: releases
        token:
          secure: Dq+aYoeFO+nUUwHzXPyMP3p4vOynLHMiZ91RoE3C/+pq4c1NeJIi2/7KUYdNaAgUvU8RVRlCuwNtd4mju/WSvMbYY59hWpv8Xj1mp6gVuvPFWMSDeT4aJKaXiU+ONSi7Zt5NnxeIQ+QKMUHIr1E8EKpTSKljUSiey8veYyuyzWgXqVmx7akmknSdLSk3VNqtbb38S4PiKt6Oq2lM12mouhPIZE6VVIALzVe2A8Jr0fR8OAyQog0g6inqJ1xg5KcMj2NMTI/1m7x8Av2KS9hbvEwen0Py4XBFmAxGE1oJu6k3UV81PEPqh3jvMfDp5klwV32svJEZzgQDHZYM+Nm48alomLgnHn/ffeRU8J5Z1yzTItW93HtuK1SLte7s9a/poQrljKSue2IkLdlCcHo3kbragGOhW/16ix2mPniBlwq8BzB6IjasErvJ241KlRXkR6ZNL4LJeToOmJQwiK2yaBrWRGS0xH2hj0OJdwCLHAKGaN5H3lWu07QNAHCIZcwFicSwVo34Wh25W0m3uJrQbxl77XFzBY2TfMpILcTVktk4hZbq5m52gLU2VB65Ew70rQszMxzLWa5dKSoSdncodMP17pWuEK5YuvZt0ZUONqPGlh1ETNtaPqGy7wXv/ddgQRy5mZuyjKB3PADcbY2jURuaoBgJUXz7HmEFVZKxsfU=
        file: dist/**/**
        file_glob: true
        overwrite: true
        cleanup: false
        on:
          tags: true
          repo: codeenigma/ce-dev
    - name: Documentation.
      if: branch = '1.x'
      addons:
        apt:
          packages:
          - p7zip-full
          - libnss3-tools
          - wget
      install:
        - wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/mkcert-v1.4.1-linux-amd64 -O /tmp/mkcert
        - sudo mv /tmp/mkcert /usr/local/bin
        - sudo chmod +x /usr/local/bin/mkcert
        - curl -sL https://raw.githubusercontent.com/codeenigma/ce-dev/1.x/install.sh | /bin/sh -s -- linux
      script: 
        - cd
        - git clone https://github.com/codeenigma/wikis2pages.git
        - cd wikis2pages
        - /bin/sh init.sh https://$GITHUB_TOKEN@github.com/codeenigma/ce-dev.git
        - /bin/sh set-current.sh ce-dev-travis
        - docker exec --user ce-dev --workdir /home/ce-dev/deploy/live.local wikis2pages-hugo hugo
        - /bin/sh .travis-push.sh