language: c
os: linux
before_install:
 - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
 - wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/mkcert-v1.4.1-linux-amd64 -O /tmp/mkcert
 - sudo mv /tmp/mkcert /usr/local/bin
 - sudo chmod +x /usr/local/bin/mkcert
install:
- yarn install
jobs:
  include:
    - name: Lint
      os: linux
      install:
        - yarn install
      script: 
        - yarn eslint src
      language: node_js
      node_js: 12
    - name: Pack
      os: linux
      script: oclif-dev pack
      language: node_js
      node_js: 12
    - name: Build and test
      os: linux
      language: c
      addons:
        apt:
          packages:
          - p7zip-full
          - libnss3-tools
          - wget
      install:
        - yarn install
        - wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/mkcert-v1.4.1-linux-amd64 -O /tmp/mkcert
        - sudo mv /tmp/mkcert /usr/local/bin
        - sudo chmod +x /usr/local/bin/mkcert
      script: 
        - /bin/sh docker-images/export.sh latest
        - /bin/sh templates/test.sh
    - name: Build and publish
      os: linux
      language: c
      addons:
        apt:
          packages:
          - p7zip-full
          - libnss3-tools
          - wget
      install:
        - yarn install
        - wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/mkcert-v1.4.1-linux-amd64 -O /tmp/mkcert
        - sudo mv /tmp/mkcert /usr/local/bin
        - sudo chmod +x /usr/local/bin/mkcert
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      script:
        - /bin/sh docker-images/export.sh latest
        - /bin/sh templates/test.sh