addons:
  apt:
    packages:
    - p7zip-full
language: node_js
node_js:
- 10
install:
- npm install
script:
- oclif-dev pack
deploy:
  provider: releases
  api_key:
    secure: KQ309vKstXn4PCVLAyrX2yERCKG62dWW4JRYij1NQ1uVUsrMAQE3nDpbB3mT7r1+t8F7H8E9G8tZO97eFE1X+irXKetGbBY79dcekzFUKAefSqISJyHl6cUADFl1jPYWh69U/m/YH6cwXH6yJ091L+mQROmMuYGmnHuz+Y5hyR0daT5TrUZ8F868B8+ZWcsk9u223tAU0NnKRCPOGTymjLRoTScyvm0jZetQ5Pu7hQVGLaBMgAvFknlbHSrRDsCX2tYKzJpwJX3rgsLNcoEviatW1iR6NFe+BH8YCnhillkGeU7weIKCjCRk+BDaLkJH/p3HxQ2HiJqK498VBs+cwfXpgvZbOyELLmNyFoNBQLqpGtwqC0tvuJ2HrRFTmxi2Vv1Kve/lCG45EcUSxYQzUIGZn/P+JMJ4s6hB1r6APODmcOfe6bUdDkMMl3otErj46+TiwEmviEqG0Cr9kce9jZxO1CVl3l7UFx757Izklb2orC4YXZNLHZirCaDWqppM2sKclABrvyxM3IuZc2bW6sTlBeh8b3d0i9tx1fdBzmdCvUpPE012A9MsKUPQ+WJ8KQ6CqvxhRdtD1MkPWvEZ4wFYSsPzmnD4bs+La8BuJdD/mkoOWR7j1gaVIXN8JfiwmHgCLmITGLAn+fkZ6o5GgG5QKKxxEWO+QByRmM4ruXs=
  file: dist/**/**
  on:
    repo: pm98zz-c/ce-dev
    branch: 1.x
  edge: true
  file_glob: true
  overwrite: true
  cleanup: false
  draft: true