addons:
  apt:
    packages:
    - p7zip-full
language: node_js
node_js:
- 10
install:
- npm install
script:
- oclif-dev pack
deploy:
  provider: releases
  api_key:
    secure: h7sPZ2NJWlJPR4XDZ/b880L3jLyK3AK1wUayyTpzfvzIR/xkhL1PpfuH3r3ICc4TY0CQkcd8I7pNwZBrqAVHT8PuxyA8naIuZlikycUWw0CPNODfOvLXX6Bs4MytnEPW8NLSCFVYd2e4COrrxYLUyaXwPOnEO1cQEZ5b6LbQaJFdenypSZsiUZW/5YtjUBRXsSX5XfgQEtOqjM4tBnZau6SwI36+ef4n+AOZun4RkxWVaOsqpENXjjIZezNRYCoC0TKgOTJBuTDhCRE1ZS7jjz+VhoBlCErr5fPeilEq37ABTPZplrmuVm1Y0Nf3A0Tup4v4HKK9zXZvMlGogswSZxQ68UVWWfThadyehipXLOYj97gj+rVWZa+mBMWW2y5tjxkt9L4lt4GtgLDgxpC0dQBSPiSC2nOxwADw9OsyPTkQXNw/smnppEqvnvzPRzx6QOAGGJ4V5aIesAY9WItt0aYLsnjyOfC+gGnfYOxEZ9x8IQfZJwsp0PAXsSVU/n7DYKrIYHpaTLdvMOpqvmLRnvZdlwz7H8nP3+RITO0r4UV8ouzyFI9fbNZF+BGpHzG0UEj7rnwvNzkp6y+n78jQ+RLdzYU8z4faGR2CbcemayKl1/ta5T10AE66H6P2SYxjrQxPy+Hj36s2kslLA75AhHMCwnEIn9F7wCSCwnOd6Os=
  file: dist/**/**
  on:
    branch: 1.x
