ce-dev-local:
  src: https://github.com/codeenigma/ce-dev.git
  src_branch: 1.x
  src_subdir: 'docs'
  dest: https://github.com/codeenigma/ce-dev-docs.git
  dest_branch: master
  dest_subdir: 1.x
  title: ce-dev
  type: doc
  base_url: https://codeenigma.github.io/ce-dev-docs/1.x
ce-dev-travis:
  src: https://$GITHUB_TOKEN@github.com/codeenigma/ce-dev.git
  src_branch: 1.x
  src_subdir: 'docs'
  dest: https://$GITHUB_TOKEN@github.com/codeenigma/ce-dev-docs.git
  dest_branch: master
  dest_subdir: 1.x
  title: ce-dev
  type: doc
  base_url: https://codeenigma.github.io/ce-dev-docs/1.x