---
- hosts: localhost
  become: true
  vars:
    - _domain_name: ci.example.com
    - _ce_provision_build_tmp_dir: /tmp
    - _ce_provision_data_dir: /tmp
    - is_local: true
    - _env_type: utility
    - ce_provision:
        own_repository: https://github.com/codeenigma/ce-provision.git
        own_repository_branch: 1.x
        own_repository_skip_checkout: false
        config_repository: https://github.com/codeenigma/ce-dev-ce-provision-config.git
        config_repository_branch: 1.x
        config_repository_skip_checkout: false
        username: controller
        local_dir: /home/controller/ce-provision
        groups: []
        galaxy_custom_requirements_file: ""
  roles:
    - _init
    - ce_provision
    - _exit
