version: "3.7"
x-ce_dev:
  registry: localhost:5000
  project_name: {{ project_name }}
  provision: 
    - ce-dev/ansible/provision.yml
  deploy: 
    - ce-dev/ansible/deploy.yml
services:
  web:
    x-ce_dev:
      host_aliases:
        - www.{{ project_name }}.local
    image: codeenigma/ce-dev:1.0.0
    volumes:
      - "..:/home/ce-dev/deploy/live.{{ project_name }}_local"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ce-dev