---
- hosts: localhost
  become: yes
  vars:
    - _domain_name: example.com
    - _ce_provision_build_tmp_dir: /tmp
    - _ce_provision_data_dir: /tmp
    - is_local: yes
    - _env_type: utility
    - ce_deploy:
        own_repository: https://github.com/codeenigma/ce-deploy.git
        config_repository: https://github.com/codeenigma/ce-dev-ce-deploy-config.git
        own_repository_branch: 1.x
        config_repository_branch: 1.x
        username: ce-dev
        local_dir: /home/ce-dev/ce-deploy
        groups: []
    - ce_provision:
        own_repository: https://github.com/codeenigma/ce-provision.git
        own_repository_branch: 1.x
        own_repository_skip_checkout: false
        config_repository: https://github.com/codeenigma/ce-dev-ce-provision-config.git
        config_repository_branch: 1.x
        config_repository_skip_checkout: false
        username: ce-dev
        local_dir: /home/ce-dev/ce-provision
        groups: []
  roles:
    - ce_provision
    - ce_deploy
