---

- hosts: localhost
  become: yes
  vars:
    - is_local: yes
    - env_type: utility
    - ansible_deploy:
        own_repository: https://github.com/codeenigma/ansible-deploy.git
        config_repository: https://github.com/codeenigma/ce-dev-ansible-deploy-config.git
        username: ce-dev
        local_dir: /home/ce-dev/ansible-deploy
        groups: []
    - ansible_provision:
        own_repository: https://github.com/codeenigma/ansible-provision.git
        config_repository: https://github.com/codeenigma/ce-dev-ansible-provision-config.git
        username: ce-dev
        local_dir: /home/ce-dev/ansible-provision
        groups: []
  roles:
    - ansible_provision
    - ansible_deploy