---
- hosts: localhost
  become: true
  vars:
    - _domain_name: example.com
    - _ce_provision_build_tmp_dir: /tmp
    - _ce_provision_data_dir: /tmp
    - _ce_provision:
        username: ce-dev
    - is_local: true
    - _env_type: utility
    - ce_deploy:
        venv_path: "/home/{{ _ce_provision.username }}/ansible"
        venv_command: /usr/bin/python3 -m venv
        own_repository: https://github.com/codeenigma/ce-deploy.git
        config_repository: https://github.com/codeenigma/ce-dev-ce-deploy-config.git
        own_repository_branch: 1.x
        config_repository_branch: 1.x
        username: ce-dev
        new_user: true
        key_name: id_rsa.pub
        local_dir: /home/ce-dev/ce-deploy
        ce_provision_dir: "/home/ce-dev/ce-provision"
        groups: []
        galaxy_custom_requirements_file: ""
        upgrade_galaxy:
          enabled: false
    - ce_provision:
        venv_path: "/home/{{ _ce_provision.username }}/ansible"
        venv_command: /usr/bin/python3 -m venv
        own_repository: https://github.com/codeenigma/ce-provision.git
        own_repository_branch: 2.x
        own_repository_skip_checkout: false
        config_repository: https://github.com/codeenigma/ce-dev-ce-provision-config.git
        config_repository_branch: 1.x
        config_repository_skip_checkout: false
        username: ce-dev
        new_user: true
        key_name: id_rsa.pub
        local_dir: /home/ce-dev/ce-provision
        groups: []
        contrib_roles:
          - directory: wazuh
            repo: https://github.com/wazuh/wazuh-ansible.git
            branch: stable
          - directory: systemd_timers
            repo: https://github.com/vlcty/ansible-systemd-timers.git
            branch: master
        galaxy_custom_requirements_file: ""
        galaxy_roles_directory: "/home/{{ _ce_provision.username }}/.ansible/roles"
        upgrade_galaxy:
          enabled: false
  roles:
    - debian/ce_provision
    - debian/ce_deploy
