---
- hosts: localhost
  become: true
  vars:
    - _domain_name: example.com
    - _ce_provision_build_tmp_dir: /tmp
    - _ce_provision_data_dir: /tmp
    - _ce_provision:
        username: ce-dev
    - is_local: true
    - _env_type: utility
    - ce_deploy:
        own_repository: https://github.com/codeenigma/ce-deploy.git
        config_repository: https://github.com/codeenigma/ce-dev-ce-deploy-config.git
        own_repository_branch: 1.x
        config_repository_branch: 1.x
        username: ce-dev
        new_user: true
        key_name: id_rsa.pub
        local_dir: /home/ce-dev/ce-deploy
        ce_provision_dir: "/home/ce-dev/ce-provision"
        groups: []
        galaxy_custom_requirements_file: ""
        upgrade_galaxy:
          enabled: false
    - ce_provision:
        own_repository: https://github.com/codeenigma/ce-provision.git
        own_repository_branch: 1.x
        own_repository_skip_checkout: false
        config_repository: https://github.com/codeenigma/ce-dev-ce-provision-config.git
        config_repository_branch: 1.x
        config_repository_skip_checkout: false
        username: ce-dev
        new_user: true
        key_name: id_rsa.pub
        local_dir: /home/ce-dev/ce-provision
        groups: []
        galaxy_custom_requirements_file: ""
        galaxy_roles_directory: "/home/{{ _ce_provision.username }}/.ansible/roles"
        upgrade_galaxy:
          enabled: false
  roles:
    - ce_provision
    - ce_deploy
