version: "3.7"
x-ce_dev:
  registry: localhost:5000
  project_name: {{ project_name }}
  provision: 
    - ce-dev/ansible/provision.yml
  deploy: 
    - ce-dev/ansible/deploy.yml
services:
  {{ project_name }}:
    image: codeenigma/ce-dev-1.x:latest
    x-ce_dev: {}