---
- hosts: localhost

  tasks:
    - name: Create target directory.
      synchronize:
        src: "{{ project_type }}/"
        dest: "/home/ce-dev/.ce-dev-cache/{{ project_name }}"
    - name: Init git repo.
      command: git init
      args:
        chdir: "/home/ce-dev/.ce-dev-cache/{{ project_name }}"
    - name: Generate docker compose template.
      template:
        src: "{{ project_type }}/ce-dev/ce-dev.compose.yml.j2"
        dest: "/home/ce-dev/.ce-dev-cache/{{ project_name }}/ce-dev/ce-dev.compose.yml"
    - name: Generate docker compose prebuilt template.
      template:
        src: "{{ project_type }}/ce-dev/ce-dev.compose.prebuilt.yml.j2"
        dest: "/home/ce-dev/.ce-dev-cache/{{ project_name }}/ce-dev/ce-dev.compose.prebuilt.yml"
    - name: Generate provision playbook.
      template:
        src: "{{ project_type }}/ce-dev/ansible/provision.yml.j2"
        dest: "/home/ce-dev/.ce-dev-cache/{{ project_name }}/ce-dev/ansible/provision.yml"
    - name: Generate deploy playbook.
      template:
        src: "{{ project_type }}/ce-dev/ansible/deploy.yml.j2"
        dest: "/home/ce-dev/.ce-dev-cache/{{ project_name }}/ce-dev/ansible/deploy.yml"
