---

- hosts: {{ project_name }}-web
  become: yes
  vars:
    - domain_name: www.{{ project_name }}.local
    - project_name: {{ project_name }}
    - mysql_client:
        host: {{ project_name }}-db
        user: root
        password: ce-dev
  {% raw %}
    - env_type: dev
    - nginx:
        domains:
          - server_name: "{{ domain_name }}"
            access_log:  "/var/log/nginx/access.log"
            error_log:  "/var/log/nginx/error.log"
            error_log_level:  "notice"
            webroot:  "/home/{{ deploy_user.username }}/deploy/live.{{ project_name }}_local/web"
            project_type:  "drupal8"
            ssl_certificate: "/etc/nginx/ssl/ssl_self_signed/{{ domain_name }}.crt"
            ssl_certificate_key: "/etc/nginx/ssl/ssl_self_signed/{{ domain_name }}.key"
            is_default: yes
            https_redirect: no
            ratelimitingcrawlers: no
    - php:
        version:
          - 7.3
{% endraw %}
  tasks:
    - import_role:
        name: _meta/common_base
    - import_role:
        name: mysql_client
    - import_role:
        name: php-cli
    - import_role:
        name: php-fpm
    - import_role:
        name: nginx