- hosts: {{ project_name }}-web
  become: yes
  vars:
    - domain_name: www.{{ project_name }}.local
    - project_name: {{ project_name }}
    - mysql_client:
        host: {{ project_name }}-db
        user: root
        password: ce-dev
  {% raw %}
    - env_type: dev
    - nginx:
        domains:
          - server_name: "{{ domain_name }}"
            access_log:  "/var/log/nginx-access.log"
            error_log:  "/var/log/nginx-error.log"
            error_log_level:  "notice"
            webroot:  "/home/ce-dev/deploy/live.local/web"
            project_type:  "drupal8"
            ssl_certificate: "{{ _ce_dev_mkcert_base}}/{{ domain_name }}.pem"
            ssl_certificate_key: "{{ _ce_dev_mkcert_base}}/{{ domain_name }}-key.pem"
            https_redirect: no
            ratelimitingcrawlers: no
            is_default: yes
            servers:
              - port: 80
                ssl: no
                https_redirect: yes
              - port: 443
                ssl: yes
                https_redirect: no
            upstreams: []
    - php:
        version:
          - 7.4
{% endraw %}
  tasks:
    - apt:
        update_cache: yes
    - import_role:
        name: _meta/common_base
    - import_role:
        name: mysql_client
    - import_role:
        name: php-cli
    - import_role:
        name: php-fpm
    - import_role:
        name: nginx