name: Lint the codebase

# Run this workflow every time a new PR is created
on: pull_request

jobs:
  # See https://github.com/marketplace/actions/run-eslint
  # ESLint now built in to GitHub Actions
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn run eslint ./src
