name: '2.x: Build the ce-dev binaries and images'

# Run this workflow only manual.
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      # Uses https://oclif.io/
      - name: Pack the JS
        run: yarn oclif pack tarballs --targets=linux-arm,linux-x64,darwin-x64 --no-xz
      - name: Rename the dist/* files
        run: yarn renamedist
      # We build mkcert from source because releases are broken
      # The last step sets ce-dev config to NOT use sudo because this causes docker image push problems
      - name: Install build and publish dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full libnss3-tools wget
          cd /tmp
          wget https://go.dev/dl/go1.22.1.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          git clone https://github.com/FiloSottile/mkcert && cd mkcert
          go build -ldflags "-X main.Version=$(git describe --tags)"
          sudo mv ./mkcert /usr/local/bin && cd ../
          sudo chmod +x /usr/local/bin/mkcert
          rm -Rf mkcert
          mkdir -p ~/.config/ce-dev
          touch ~/.config/ce-dev/preferences-2.x.yml
          echo 'docker_bin: docker' > ~/.config/ce-dev/preferences-2.x.yml
          echo 'docker_compose_bin: docker compose' >> ~/.config/ce-dev/preferences-2.x.yml
          echo 'mkcert_bin: mkcert' >> ~/.config/ce-dev/preferences-2.x.yml
      - name: Build and push Docker images
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          /bin/sh docker-images/export.sh --version latest --image-name ce-dev --dockerfile-path base --push
          /bin/sh docker-images/export.sh --version latest --image-name ce-dev-controller --dockerfile-path controller --push
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          sudo chmod +x bin/run.js
          /bin/sh templates/prebuild.sh --push
       # Uses https://github.com/marketplace/actions/gh-release
       # Pack step places the build artifacts in ./dist
      - name: Publish new ce-dev binaries
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/**
          body_path: RELEASE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
