name: '2.x: Linux - Build ce_dev binaries, images and templates (test)'

on:
  push:
    branches:
      - 2.x-devel
  pull_request:
    types:
      - opened
    branches:
      - 2.x-devel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '2.x-devel'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install modules
        run: yarn install --production=false --global
      - name: List modules installed
        run: yarn list --depth=0
      - name: Pack the JS
        run: yarn oclif pack tarballs --targets=linux-x64,linux-arm,linux-arm64 --no-xz
      - name: Rename the dist/* files
        run: yarn renamedist
      # We build mkcert from source because releases are broken
      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full libnss3-tools wget
          cd /tmp
          wget https://go.dev/dl/go1.22.1.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          git clone https://github.com/FiloSottile/mkcert && cd mkcert
          go build -ldflags "-X main.Version=$(git describe --tags)"
          sudo mv ./mkcert /usr/local/bin && cd ../
          sudo chmod +x /usr/local/bin/mkcert
          rm -Rf mkcert
      - name: Build and test
        run: |
          /bin/sh docker-images/export.sh --version devel --image-name ce-dev --dockerfile-path base-devel
          /bin/sh docker-images/export.sh --version devel --image-name ce-dev-controller --dockerfile-path controller-devel
          sudo chmod +x bin/dev.js
          /bin/sh templates/prebuild.sh --template ce-dev-devel.compose.yml --devel
      - name: Testing templates
        run: |
          sudo chmod +x bin/dev.js
          /bin/sh templates/prebuild.sh --template ce-dev-devel.compose.yml --devel
