name: Test image builds on PR

# Run this workflow at 6:30 every day and on each PR
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      # Uses https://oclif.io/
      # Not strictly necessary here, but ensures the packing works
      - name: Pack the JS
        run: yarn oclif-dev pack
      # We build mkcert from source because releases are broken
      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full libnss3-tools wget
          cd /tmp
          wget https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          git clone https://github.com/FiloSottile/mkcert && cd mkcert
          go build -ldflags "-X main.Version=$(git describe --tags)"
          sudo mv ./mkcert /usr/local/bin && cd ../
          sudo chmod +x /usr/local/bin/mkcert
          rm -Rf mkcert
      - name: Verify cgroup used
        run: docker info
      - name: Build and test
        run: |
          /bin/sh docker-images/export.sh latest
          docker ps
          /bin/sh templates/prebuild.sh
