name: Build the ce-dev binaries and images

# Run this workflow only on a push/merged PR to branch 1.x with valid tags
on:
  push:
    tags:
    - 1.*
  workflow_dispatch:
    tags:
    - 1.*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      # Uses https://oclif.io/
      - name: Pack the JS
        run: yarn oclif-dev pack
      # We build mkcert from source because releases are broken
      # The last step sets ce-dev config to NOT use sudo because this causes docker image push problems
      - name: Install build and publish dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full libnss3-tools wget
          cd /tmp
          wget https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          git clone https://github.com/FiloSottile/mkcert && cd mkcert
          go build -ldflags "-X main.Version=$(git describe --tags)"
          sudo mv ./mkcert /usr/local/bin && cd ../
          sudo chmod +x /usr/local/bin/mkcert
          rm -Rf mkcert
          mkdir -p ~/.config/ce-dev
          touch ~/.config/ce-dev/preferences-1.x.yml
          echo 'docker_bin: docker' > ~/.config/ce-dev/preferences-1.x.yml
          echo 'docker_compose_bin: docker-compose' >> ~/.config/ce-dev/preferences-1.x.yml
          echo 'mkcert_bin: mkcert' >> ~/.config/ce-dev/preferences-1.x.yml
      - name: Build and push Docker images
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          /bin/sh docker-images/export.sh latest --push
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          /bin/sh templates/prebuild.sh --push
       # Uses https://github.com/marketplace/actions/gh-release
       # Pack step places the build artifacts in ./dist
      - name: Publish new ce-dev binaries
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/**
          body_path: RELEASE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
